# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca2375f4b2620a33003552050aada042da389e5ee1a58f91050199531fe4c3f8ecd7c28257e746f5d1f83caa0e88447729fde69bff8ca7cffe1cab323777fda5

test:
  secret_key_base: 3e3672560d58060803f3365a5498c9c9e95885149b2208e0343d1781cb84de1eda7614b40db2599680e851f0e46dc769dca23dc05eee59b47f9e3328eb75d85a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
